export * from "./AboutPageSections";
export * from "./BranchesSection";
export * from "./CategorysList";
export * from "./Footer";
export * from "./Header";
export * from "./Heroes";
export * from "./RehabilitationBody";
export * from "./ServicesSection";
export * from "./TreatmentAndDetailSection";
